CREATE DATABASE DBCRUD
GO

USE DBCRUD;
GO

CREATE TABLE Usuario (
id INT IDENTITY NOT NULL,
nome VARCHAR(100) NOT NULL ,
email VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL,
statusUsuario VARCHAR(10) NOT NULL,
PRIMARY KEY(id)
);

INSERT INTO USUARIO VALUES 
('ENZO BRITO', 'ENZO@GMAIL.COM', '123', 'ATIVO');
INSERT INTO USUARIO VALUES 
('ANA', 'ANA@GMAIL.COM', '123', 'ATIVO');
INSERT INTO USUARIO VALUES 
('JOSÉ', 'JOSE@GMAIL.COM', '123', 'ATIVO');

select * from Usuario;